### ISSUE TITLE
The argument order of glmm_store3() and glmm_store() is not consistent.

### ISSUE THREAD

**Issue by superbigio** [recp/cglm#101]
glm_store3() arguments are swapped compared to glm_store().
Luckily glm_store3() doesn't seem to be used anywhere in the codebase.
Making it consistent with glm_store() would be trivial and it would not break anything.

I propose changing the argument order of glm_store3() so that the float pointer/array (destination) comes 1st and the 128-bit SSE vector argument (source) comes 2nd.

Notice that both SSE and Neon intrinsics follow the same convention.
(float pointer/array 1st, SIMD vector 2nd)

**Comment by recp** [comment]
I you would like to update it, a PR is welcome, otherwise I can update it asap.

**Comment by superbigio** [comment]
No problem, I will create a PR right away.
