### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by recp** [recp/cglm#104]
Currently **cglm** uses **cmocka** for tests, recently I thought that maybe we can use `assert()` and make our own test runner. Because the only build dependency is **cmocka** which is for tests, writing our own runner will make **cglm** zero-dependency library

-----
After we made tests more stable then all Pull Requests or features must come with test cases (if the changes are related to coding)

**Comment by superbigio** [comment]
Yes, I agree. I would definitely get rid of the cmocka dependency. Functions in this API are pretty easy to test. We could write our own test suite.

**Comment by recp** [comment]
I have created a PR to drop cmocka and implement custom unit test suite

https://github.com/recp/cglm/pull/105

Any feedbacks are welcome, I'm considering to merge it asap.

**Comment by recp** [comment]
This is implemented at https://github.com/recp/cglm/pull/105

Now let's write tests for every cases for every CPU arch and make **cglm** more robust.
