### ISSUE TITLE
make install fails due to duplicate line in Makefile.am

### ISSUE THREAD

**Issue by pm4gh** [recp/cglm#108]
On Ubuntu 19.10, make install fails at this point :

 /usr/bin/install -c -m 644 include/cglm/version.h include/cglm/common.h include/cglm/types.h include/cglm/types-struct.h include/cglm/cglm.h include/cglm/call.h include/cglm/struct.h include/cglm/cam.h include/cglm/io.h include/cglm/mat4.h include/cglm/mat3.h include/cglm/affine.h include/cglm/vec3.h include/cglm/vec3-ext.h include/cglm/vec4.h include/cglm/vec4-ext.h include/cglm/euler.h include/cglm/util.h include/cglm/quat.h include/cglm/affine-mat.h include/cglm/plane.h include/cglm/frustum.h include/cglm/box.h include/cglm/color.h include/cglm/project.h include/cglm/sphere.h include/cglm/ease.h include/cglm/curve.h include/cglm/bezier.h include/cglm/bezier.h include/cglm/applesimd.h '/usr/local/include/cglm'
/usr/bin/install: will not overwrite just-created '/usr/local/include/cglm/bezier.h' with 'include/cglm/bezier.h'
make[1]: *** [Makefile:1033: install-cglmHEADERS] Error 1

This is caused by the duplicate entry for include/cglm/bezier.h in the cglm_HEADERS in Makefile.am

**Comment by recp** [comment]
Hi @pm4gh 

Thanks for reporting this, would you mind to fix that with a PR ? Otherwise I'll fix it asap ;)

**Comment by pm4gh** [comment]
Put the fix in yourself, please.

I'm not very familiar with git and totally new to github. Looked into what a PR is, seems an elegant way to offer changes, but isn't it a little over the top for reporting a trivial issue like this ? Or is this just how things are done on github ?

**Comment by recp** [comment]
Duplicate entry is removed in https://github.com/recp/cglm/commit/9987e1374b93dcad4e8e61b83a5286accb12d1dc
