### ISSUE TITLE
Build error on Android

### ISSUE THREAD

**Issue by kinnefix** [recp/cglm#114]
I am trying to use this library for my project.
On running make, I get the following errors:
[output.log](https://github.com/recp/cglm/files/4058435/output.log)

**Comment by kinnefix** [comment]
And of course, the build succeeds if I make a modification to file include/cglm/simd/intrin.h to disable definition of CGLM_NEON_FP.

**Comment by recp** [comment]
Hello @kinnefix 

Thanks for reporting this issue 

It seems there are type casting errors (`float32x4_t` to `float32x2_t`) this can be fix by creating temp variables for them instead of assigning them to float34x4_t...

I will fix it asap but if you want to fix it before me a PR is welcome ;)

**Comment by recp** [comment]
@kinnefix can you try to build using the PR: https://github.com/recp/cglm/pull/115
