### ISSUE TITLE
cglm rotate differs from glm rotate

### ISSUE THREAD

**Issue by PortStone** [recp/cglm#118]
GLM: 
```
glm::mat4 trans = glm::mat4(1.0f);
trans = glm::rotate(trans, glm::radians(90.0f), glm::vec3(0.0, 0.0, 1.0));
```
CGLM:
```
mat4 trans = GLM_MAT4_IDENTITY_INIT;
glm_rotate(trans, glm_rad(90.0f), (vec3){0.0f, 0.0f, 1.0f});
```

Output of GLM:
`mat4x4((-0.000000, 1.000000, 0.000000, 0.000000), (-1.000000, -0.000000, 0.000000, 0.000000), (0.000000, 0.000000, 1.000000, 0.000000), (0.000000, 0.000000, 0.000000, 1.000000))`
Output of CGLM:
```
Matrix (float4x4):
        |-0.0000        -1.0000 0.0000  0.0000|
        |1.0000 -0.0000 0.0000  0.0000|
        |0.0000 0.0000  1.0000  0.0000|
        |0.0000 0.0000  0.0000  1.0000|
```

As you can see (1,2) and (2,1) are different. Did I used it wrong?

**Comment by recp** [comment]
Hello @PortStone 

**glm** may printed matrix as columns. In your example the result seems same if this is correct. For instance, in your example in glm the first column is `(-0.000000, 1.000000, 0.000000, 0.000000)`, in cglm that is `-0.0000, 1.0000, 0.0000, 0.0000`, see

If `(-0.000000, 1.000000, 0.000000, 0.000000)` is row then the result would be different :S 

----

**cglm** stores matrices as columns but when printing, it prints that as human readable format. In that case:

`|-0.0000        -1.0000 0.0000  0.0000|` is the first row, not column. 

But don't forget get `mat[0]` will give you the first column and `mat[0][3]` will give you the fist column's 3rd element in **cglm**.

Do you still think that there is an error?

**Comment by PortStone** [comment]
Hello @recp 
thank you for the fast response. I didn't knew that and now it works. Thanks for creating the library, too.

This may help for fixing alignment:

![2020-02-20-18-30-12](https://user-images.githubusercontent.com/27790087/74962086-802e9300-540f-11ea-9510-126ec8f3d18c.gif)

**Comment by recp** [comment]
@PortStone alignment has been fixed and print functions are improved ;) check this PR: https://github.com/recp/cglm/pull/140
