### ISSUE TITLE
Strange behaviour after calling glm_vec3_zero()

### ISSUE THREAD

**Issue by Daniel-Schreiber-Mendes** [recp/cglm#119]
Hello; first I wanted to thank you for this great library. But about my problem: I have a Transform-Component that I can attach to entitys and change their scale, position and rotation. 
```c
typedef struct
{
	float rotation;
	vec3 position;
	vec3 scale;
}
Transform;
```
I can manipulate the values and everything works just fine. But when I call 
` glm_vec3_zero(transformInstance->position);` at first everything seems to work. When I end the program tough and free all my memory, I get this error `free(): invalid next size (fast)`. If I comment out this line everything works again. What's even stranger is that I don't have the same problem with the scale vector! What could the source for the problem be? Thanks for your help

**Comment by recp** [comment]
Hi @Daniel-Schreiber-Mendes 

> first I wanted to thank you for this great library

Thanks

Did you solve your problem may I ask? cglm doesn't alloc any memory on the heap. For troubleshooting:

https://cglm.readthedocs.io/en/latest/troubleshooting.html
https://cglm.readthedocs.io/en/latest/getting_started.html

best,
r.
