### ISSUE TITLE
mat2 header not copied when installing

### ISSUE THREAD

**Issue by noah1786** [recp/cglm#120]
I don't know much about autogen tools, but the makefile has this as cglm_simd_sse2_HEADERS:
```
cglm_simd_sse2_HEADERS = include/cglm/simd/sse2/affine.h \
                         include/cglm/simd/sse2/mat4.h \
                         include/cglm/simd/sse2/mat3.h \
                         include/cglm/simd/sse2/quat.h
```
even though, in include/cglm/simd/sse2, there is mat2.h .

When I try to compile a source file including cglm, this results in the error
```
/usr/local/include/cglm/mat2.h:40:12: fatal error: simd/sse2/mat2.h: No such file or directory
 #  include "simd/sse2/mat2.h"
```
Fixed by adding it to the makefile manually.
running `Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`

**Comment by recp** [comment]
Hi @noah1786 

Thanks for reporting this. This must be fixed with https://github.com/recp/cglm/commit/69b5584f112c73af211da7b6d0918b87dd8e090b

**Comment by recp** [comment]
Also check this release [v0.7.1](https://github.com/recp/cglm/releases/tag/v0.7.1), can you try to build and install again please

**Comment by noah1786** [comment]
Sorry to take so long to get back to you. I didn't have any problems re-building it on the same machine or building it on a different machine.

**Comment by recp** [comment]
@noah1786 thanks
