### ISSUE TITLE
Superfluous declaration of glm_mat4_mul() in affine.h

### ISSUE THREAD

**Issue by pm4gh** [recp/cglm#123]
There is a declaration of glm_mat4_mul() around line 45 of include/cglm/affine.h that doesn't seem useful since the function's definition is included a few lines earlier via mat4.h, and causes the warning below if compiled with gcc's -Wredundant-decls flag.

`In file included from DrawOGL.c:27:`
`../cglm/affine.h:45:1: warning: redundant redeclaration of 'glm_mat4_mul' [-Wredundant-decls]`
`   45 | glm_mat4_mul(mat4 m1, mat4 m2, mat4 dest);`
`      | ^~~~~~~~~~~~`
`In file included from ../cglm/affine.h:40,`
`                 from DrawOGL.c:27:`
`../cglm/mat4.h:278:1: note: previous definition of 'glm_mat4_mul' was here`
`  278 | glm_mat4_mul(mat4 m1, mat4 m2, mat4 dest) {`
`      | ^~~~~~~~~~~~`

**Comment by recp** [comment]
Hi @pm4gh 

Would you like to remove these redundant forward declarations in `affine.h` and in other headers? Otherwise I'll fix that asap.

Thanks.

**Comment by recp** [comment]
This is fixed by https://github.com/recp/cglm/commit/7eada03909017982174460a5ec714f9c74207f35

best,
r.
