### ISSUE TITLE
Can not work on Windows 10 (VS2017) 

### ISSUE THREAD

**Issue by CHN-STUDENT** [recp/cglm#13]
Hello,
When I try to build and use it on my computer ( OS:Windows 10  IDE: Visual Studio 2017 )
but it can not work.
Here are error info:
(I used google translate to translate from Chinese to English,because i do not have English version of Visual Studio.)

```
1> ------ Startup Generated: Project: Project1, Configuration: Debug Win32 ------
1> cglmtest.cpp
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (323): error C2059: Syntax error: "="
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (324): error C2059: Syntax error: "="
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (325): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (326): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (327): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (328): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (358): warning C4091: "": ignoring the left side of "float"
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (360): error C2059: Syntax error: "="
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (361): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (362): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (378): warning C4091: "": ignoring the left side of "float"
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (380): error C2059: Syntax error: "="
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (381): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (382): error C2100: Illegal Indirect Addressing
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (398): error C2059: Syntax error: "="
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (399): error C2059: Syntax error: "="
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (411): error C2059: Syntax error: "="
1> c: \ users \ mr.guo \ desktop \ cglm \ cglm \ include \ cglm \ cam.h (423): error C2059: Syntax error: "="
1> The operation of generating the project "Project1.vcxproj" completed - failed.
========== Generate: 0 success, 1 failure, 0 latest, 0 skip ==========
```
This is main function code:
```
/*cglmtest.cpp*/
#include <stdio.h>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include "shader_c.h"
#include "stb_image.h"
#include <cglm\cglm.h>
#define STB_IMAGE_IMPLEMENTATION

int main(void)
{

	return 0;
}
````
Please help me and please do not mind my poor English.
Thanks!

**Comment by recp** [comment]
Hello @CHN-STUDENT,

Thank you for reporting this, building on Windows seems passing: https://ci.appveyor.com/project/recp/cglm/branch/master

My main environment is macOS also I have Linux environment,
recently I removed my virtual Windows but I will install ASAP

Shouldn't  this `#include <cglm\cglm.h>` be `#include <cglm/cglm.h>` ?

**Comment by CHN-STUDENT** [comment]
@recp yes,you see i created a project named Project 1,then i wrote the main function include your header file without any function and try to compile it,but the compiler told me some errors in `cam.h`. And i am sorry for giving the error info by using the translation system.If you think you need more files or info,please tell me then i will give you.Hope you can help me,thanks!

**Comment by CHN-STUDENT** [comment]
@recp This is my project,hope you can get some info which you wanted form it.
[https://github.com/CHN-STUDENT/LearnOPENGL](https://github.com/CHN-STUDENT/LearnOPENGL)
And i am a learner who learns opengl,now i am learning about OpenGL Mathematics.Because my project need to use `C` not `C++`.So i want to hope using your cglm.

**Comment by recp** [comment]
Thank you for sharing your project, I will try to compile it successfully ASAP

> Because my project need to use C not C++

But it seems your source file (`/*cglmtest.cpp*/`) is C++ not C? 

> So i want to hope to use your cglm.

Good choice :) it is well optimized, small and fast. 

But please check header files if you have any confusion about parameters,
there should be function documentation there except some header needs to be documented
also any enhancement, feature request or bug reports are welcome. 

All functions are inline, if you want to use pre-compiled version use glmc_ prefix after including cglm/call.h. If you don't want to use pre-compiled versions then don't spend / waste time for compiling cglm

**Comment by recp** [comment]
Finally I installed Win10 and VS17

It seems you are getting these errors because **near** and **far** values 
also defined by windows headers as MACRO:
```C
minwindef.h

#define far
#define near
```

because #include <glad/glad.h> includes windows headers. 

That is funny

Possible solutions in cglm:
- Change all **near** and **far** names
- https://stackoverflow.com/questions/118774/is-there-a-clean-way-to-prevent-windows-h-from-creating-a-near-far-macro

**Comment by CHN-STUDENT** [comment]
@recp Thank you!i changed all near and far names then i solved my issue!
 And You found i my source file is the C++ source file ,i think i make a mistake because the VS only can create the C++ source file,and i need to create a C source file then add it to my project instead of creating it on VS.Thank you for your suggest!

**Comment by recp** [comment]
I also changed all near and far variable names (https://github.com/recp/cglm/commit/35d078a1ed01edbb8386818df379944d0bd07412#diff-3139ea130d2c802d9106a2232dfb161f) in camera header file. You can pull the lastest

There is also alignment issue in my todo: https://github.com/recp/cglm/issues/4 I hope you will not get error until I fixed it
