### ISSUE TITLE
Documentation for glm_mat4_mulv3

### ISSUE THREAD

**Issue by PeterOGB** [recp/cglm#147]
Documentation is missing the "last" parameter...

In the code it is defined as :
void glm_mat4_mulv3(mat4 m, vec3 v, float last, vec3 dest) 

But the documentation  says:
void glm_mat4_mulv3(mat4 m, vec3 v, vec3 dest)

**Comment by recp** [comment]
@PeterOGB thanks for letting us know. Would you like to fix that with a PR? If not, I'll do that asap.

best,
r.

**Comment by recp** [comment]
I have updated the docs to fix this issue (see https://github.com/recp/cglm/commit/62ab6c56c05fdd0c2545c1f783ad2bd180dbb196), feels free to come with any other issues... 

Thanks
