### ISSUE TITLE
Incompatible MSVC command line options

### ISSUE THREAD

**Issue by RadiatedMonkey** [recp/cglm#148]
cl : command line error D8016: '/Ox' and '/RTC1' command-line options are incompatible [...\lib\cglm\cglm.vcxproj]

I'm using MSVC 19.26.28806, and compiling for x64

**Comment by recp** [comment]
Hi @RadiatedMonkey 

Thank you for letting us know,

I tried to remove `/RTC` flag with this commit: https://github.com/recp/cglm/commit/a9ed8470b438c9bcefcbfaa703a9e3f48fddc3e6 

Can you try again by pulling master please? 

---

Resources:
[0] https://stackoverflow.com/questions/23179136/visual-studio-command-line-error-d8016-ox-and-rtc-command-line-options-a
[1] https://docs.microsoft.com/en-us/cpp/build/reference/rtc-run-time-error-checks?view=vs-2019

**Comment by RadiatedMonkey** [comment]
Sorry for my late response, but it's still not working

**Comment by recp** [comment]
Are you using CMake to build or using pre-exist cglm.vcproj inside **win/** folder? 

With this commit (https://github.com/recp/cglm/commit/c18fe8098f910f1d3a74e4464091c83fbcba7a21) I tried to remove /RTC1 

I have found solution (I guess) at https://skia.googlesource.com/third_party/sdl/+/refs/heads/master/CMakeLists.txt#225

Can you try again please?

Thanks

**Comment by RadiatedMonkey** [comment]
Looks like it's working now, thanks!

**Comment by recp** [comment]
@RadiatedMonkey great! Thanks for helping to fix this issue 🎉
