### ISSUE TITLE
Meson build support

### ISSUE THREAD

**Issue by randy408** [recp/cglm#157]
I have ported cglm to [Meson](https://mesonbuild.com/index.html), it's a single `meson.build` in the top-level directory and has similar defaults to the CMakefile, should I open a PR for it?

**Comment by recp** [comment]
Sure. 

Don't forget to add build instructions to README, docs/build.rst ... 

Thanks

**Comment by recp** [comment]
See https://github.com/recp/cglm/pull/158 ( thanks to @randy408 )
