### ISSUE TITLE
modulemap: definition in module 'cglmc' first difference is function body

### ISSUE THREAD

**Issue by recp** [recp/cglm#162]
I'm getting this error:

```
'glm_mat4_mulN' has different definitions in different modules;
definition in module 'cglmc' first difference is function body
```

when I remove `export *` in `include/module.modulemap` file error disappears. 

This line seems the problem: 

```C
#ifdef DEBUG
  assert(len > 1 && "there must be least 2 matrices to go!");
#endif
```

removing this assertion also helps.

any help to fix this ? We added this ModuleMap with https://github.com/recp/cglm/pull/160 

/cc @smumryak

**Comment by smumryak** [comment]
Hey @recp! 
Thanks for tagging me here. could you please tell me what build process have you been using to repro this error? I'll look into this.

**Comment by recp** [comment]
Hi @smumryak 

I have used Xcode to build **cglm** project and it fails due to above errors. It seems we need to update `include/module.modulemap`. Because it doesn't allow conditional builds / pre-processors... for instance  `#ifdef DEBUG ...`, removing ` export *` in .modulemap also helps if it doesn't break anything  


You can simply create a Xcode project by including all **cglm** files to it and try to build it. I didn't used and tested CMake output, fyi.

**Comment by recp** [comment]
Setting `CLANG_ENABLE_MODULES`to `NO` in **cglm** Xcode project fixed the issue for me, there is no need to module lookup for itself (maybe we could do something else here). Building with build files are also ok. 

Let's close this now.
