### ISSUE TITLE
Unexpected multiplication order in glm_rotate

### ISSUE THREAD

**Issue by mathkr** [recp/cglm#166]
I am a little confused about the order of operations when using `glm_rotate_x/y/z`.

I was expecting
```
glm_rotate_x(M, a, dest);
```
To be equivalent to **dest** = **R** * **M** (where **R** is the newly constructed rotation matrix), that is the *existing* affine transformation **M** is applied first.

Instead it seems to me that actually **dest** = **M** * **R** is the result.
See here in `affine.h`:
```
CGLM_INLINE
void
glm_rotate_x(mat4 m, float angle, mat4 dest) {
  CGLM_ALIGN_MAT mat4 t = GLM_MAT4_IDENTITY_INIT;
  float c, s;

  c = cosf(angle);
  s = sinf(angle);

  t[1][1] =  c;
  t[1][2] =  s;
  t[2][1] = -s;
  t[2][2] =  c;

  glm_mul_rot(m, t, dest);
}
```

Shouldn't it be `glm_mul_rot(t, m, dest)`?

I'm expecting `glm_rotate_x(m, a, m);` to be shorthand for:
```
mat4 rot;
glm_rotate_make(rot, a, GLM_XUP);
glm_mat4_mul(rot, m, m);                    // could also use glm_mul_rot(rot, m, m)
```

Since cglm is using column-major conventions I'm expecting the following code to print the same result twice, **but it doesn't**.
```
float pitch = -24.0f;
float yaw   = 53.0f;
{
    mat4 transform = GLM_MAT4_IDENTITY;
    glm_rotate_x(transform, glm_rad(pitch), transform);
    glm_rotate_y(transform, glm_rad(yaw), transform);
    glm_mat4_print(transform, stdout);
}
{
    mat4 transform, rotx, roty;
    glm_rotate_make(rotx, glm_rad(pitch), GLM_XUP);
    glm_rotate_make(roty, glm_rad(yaw), GLM_YUP);
    glm_mul_rot(roty, rotx, transform);
    glm_mat4_print(transform, stdout);
}
```

Am I missing something?

**Comment by recp** [comment]
Hi @mathkr 

IIRC, **glm** also uses this behavior and **cglm** adopted this behavior from **glm** (I need to test it to validate this) 

Do we want to rotate model or transformed model? Let's think about this example: 

![rot](https://user-images.githubusercontent.com/1264894/99661736-545f3d00-2a75-11eb-9111-409c242ea73e.jpg)

The cube was at origin and now it is transformed. 

---

#### Clarification:

* `glm_rotate()`,`glm_rotate_x/y/z()`, `glm_quat_rotate()` and `glm_quat_rotatev()` rotates around origin. 
* `glm_rotate_at()`, `glm_rotate_atm()` (*m* stands for make), `glm_vec3_rotate()`, `glm_quat_rotate_at()`, `glm_quat_rotate_atm()` rotates around given axis

---

1. Let's apply `glm_translate()...`,`glm_scale()...`,`glm_rotate()...`, `glm_rotate_x/y/z()...` transforms last instead first:

    Applying rotation would rotate model around origin as you can see in image [from 2 to 3] not around itself. Mixing scale, rotate and translate probably produce odd visual transforms I think. 

2. But if rotation is applied first, it would rotate around itself if model's center is origin. For instance you can create a spinning box animation in this way. 

I think **cglm** could provide applying rotation last version, like append to last or insert to first. Any feedback or comments? 

---

I'm glad to see that you discover `glm_mul_rot()`, someone other may used `glm_mat4_mul()` instead. `glm_mul()`, `glm_mul_rot()` ... are special multiplication and optimized more, even more... **cglm** provides useful helpers to make things faster and easy to use...

**Comment by mathkr** [comment]
Hey @recp  and thank you for the quick answer!

As far as I can tell that indeed seems to be the behaviour of `glm::rotate` which is in turn based on OpenGLs `glRotatef` where each call applies as a *pre-multiplication* (so is multiplied on the right side in mathematical notation). I hadn't used this family of functions before but at least now I know.

I still wonder if these functions were correctly named in the first place, since they kind of obfuscate the underlying linear algebra but since it seems that this is strongly established in the OpenGL world it is definitely not on cglm to break this convention.

> I think cglm could provide applying rotation last version, like append to last or insert to first. Any feedback or comments?

Now that my little misunderstanding is cleared up, this doesn't seem necessary (to me at least) since it can easily be done with just one extra line of code anyway. It is even documented (https://cglm.readthedocs.io/en/latest/affine.html#transforms-order) so I don't really understand how I missed it.

**Comment by recp** [comment]
@mathkr thanks,

Please come back if you face any other issues. Sometimes bugs occur and I'm (and/or other users) trying to fix them quickly

**Comment by recp** [comment]
Also any feedbacks, proposals, bug fixes, help... are welcome about function naming and for other features/implementations...
