### ISSUE TITLE
How can use the function in your cglm library to make mat4 to Glfloat?

### ISSUE THREAD

**Issue by CHN-STUDENT** [recp/cglm#17]
Today,i still learn the OpenGL from https://learnopengl.com/#!Getting-started/Transformations 
(the Chinese version: https://learnopengl-cn.github.io/01%20Getting%20started/07%20Transformations/ )

the guide book is using c++ (the glm library) and i try to use your cglm library instead of it.

When i try to define variables `mat4 a`,use your function like `glm_rotate` to calc,the guide book tell me that i need to make `mat4` to `Glfloat` to use the OpenGL function.But i can not find a way to make `mat4` to `Glfloat`?I use search tool to search your guide book,but i do not find anything...

The  OpenGL guide book code is:
```cpp
glm::mat4 trans;
trans = glm::rotate(trans, glm::radians(90.0f), glm::vec3(0.0, 0.0, 1.0));
trans = glm::scale(trans, glm::vec3(0.5, 0.5, 0.5)); 
unsigned int transformLoc = glGetUniformLocation(ourShader.ID, "transform");
glUniformMatrix4fv(transformLoc, 1, GL_FALSE, glm::value_ptr(trans));
```

My code is 
```c
mat4 trans;
vec3 a = { 0.0, 0.0, 1.0 };
glm_rotate(trans, glm_rad(90.0f), a);
vec3 b = { 0.5, 0.5, 0.5 };
glm_scale(trans,b);
unsigned int transformLoc = glGetUniformLocation(ID, "transform");
//because i do not know how to make mat4 to Glfloat,so i comment it.
//glUniformMatrix4fv(transformLoc, 1, GL_FALSE, trans);
```
So can you help me and give me some idea to solve it when you have free time?Thanks!!!
Please do not mind my poor English and my poor code.

**Comment by recp** [comment]
Hi

It is very easy! matrix is array of columns and you pass first element of array 
```C
glUniformMatrix4fv(transformLoc, 1, GL_FALSE, trans[0]);
```

I made a helper for it for my renderer:
```C
void
gkUniformMat4(GLint location, mat4 matrix) {
  glUniformMatrix4fv(location, 1, GL_FALSE, matrix[0]);
}
```

Addition, if you compile it with C compiler this could be written as (I think it is more readable):
```C
mat4 trans;

glm_rotate(trans, glm_rad(90.0f), (vec3){0.0f, 0.0f, 1.0f});
glm_scale(trans, (vec3){0.5f, 0.5f, 0.5f});
```

even

```C
mat4 trans;

glm_rotate(trans, glm_rad(90.0f), GLM_ZUP);
glm_scale(trans, (vec3){0.5f, 0.5f, 0.5f});
```

I know GLM_ZUP is not very good name here (it is actually for lookat), maybe we must define alternative name

**Comment by recp** [comment]
EDIT: 

You can't rotate it because it is not initialized. You must initialize it like this:

```C
mat4 trans = GLM_MAT4_IDENTITY_INIT;

glm_rotate(trans, glm_rad(90.0f), GLM_ZUP);
glm_scale(trans, (vec3){0.5f, 0.5f, 0.5f});
```

or you have another option here:
```C
mat4 trans;

glm_rotate_make(trans, glm_rad(90.0f), GLM_ZUP); /* creates rotation matrix */
glm_scale(trans, (vec3){0.5f, 0.5f, 0.5f});
```

`glm_rotate`, `glm_scale`, `glm_translate` assumes you pass existing transform. There are `glm_rotate_make`, `glm_scale_make`, `glm_translate_make` alternatives which assumes you don't have transform matrices

**Comment by CHN-STUDENT** [comment]
@recp Thanks for your help!!!
Your give me a good suggest because i define the  variables `mat4 a` but not initialized.I think if you do not tell me,i will make a mistake too,and I am very happy to get your help and you do not mind my poor English and my poor code.
I hope you can give your library more help guide book and more demos for our beginner.It is very useful.
Thanks for your help!!!  
:)

**Comment by recp** [comment]
Actually you don't have to initialize all matrices or vertors... It depends. 

In genereal you don't have to initialize **[out]** parameters but you must initialize **[in]** or **[in, out]** parameters. Most out parameters' name is **dest**, probably the last parameter. Some header files must be documented like vec3.h, I do that asap

I'm trying to make it more readable and easy to use, any bug report, feedback, contribution... always welcome!
