### ISSUE TITLE
Compilation error when using C++11

### ISSUE THREAD

**Issue by SanderMertens** [recp/cglm#171]
Hi, I am using cglm in a project that uses both C and C++11, and am running into a compilation error with g++:
```
/home/vagrant/bake/include/cglm/vec3-ext.h:240:40: error: exponent has no digits
  240 |   dest[0] = fminf(v[0] - floorf(v[0]), 0x1.fffffep-1f);
```

Hex digits with floating point numbers have only been added since C++17. It would be nice if this could be modified so that the code compiles with C++11.

I tested it on:
Ubuntu 20.04
g++ 9.3.0

with compiler options:
-fPIC -fvisibility=hidden -fno-stack-protector -g -O0 -std=c++0x -Wall -W -Wextra -Wno-unused-parameter -Wno-missing-field-initializers 

Awesome library btw, thanks!

**Comment by recp** [comment]
Bi @SanderMertens 

Good catch! You are right this library must allow to built with old compilers 

I just missed that Hex number :( 

A PR to fix that would be awesome, otherwise I'll try to fix it ASAP

**Comment by SanderMertens** [comment]
I created this PR: https://github.com/recp/cglm/pull/172

**Comment by recp** [comment]
@SanderMertens thanks the PR is merged, it can be updated as I mentioned in this comment  https://github.com/recp/cglm/pull/172#issuecomment-737080592
