### ISSUE TITLE
glm_aabb_sphere test incorrect

### ISSUE THREAD

**Issue by ILeonor** [recp/cglm#179]
example:
```
vec3 box[2] = {{0.f, 0.f, 0.f}, {2.f, 2.f, 2.f}};
vec4 sphere = {1.f, 1.f, 1.f, 0.5f};

glm_aabb_sphere(box, sphere); //return false
```
but the sphere is completely in the box and the test should return true.
Solid Box - Solid Sphere test from (https://github.com/erich666/GraphicsGems/blob/master/gems/BoxSphere.c) returns true

this happens due to the fact that `dmin` should increase only if `s[i] < box[0][i] || s[i] > box[1][i]`

Possible Solution:
```
float dmin = 0.f;
int   i;

for (i = 0; i < 3; ++i) {
    dmin += (s[i] < box[0][i] || s[i] > box[1][i])
            ? glm_pow2(s[i] - box[s[i] > box[1][i]][i]) : 0;
}

return dmin <= glm_pow2(s[3]);
```

P.S. sorry for my bad english

**Comment by recp** [comment]
Hi @ILeonor 

> this happens due to the fact that dmin should increase only if s[i] < box[0][i] || s[i] > box[1][i]

Good catch! Thanks for providing a solution. Would you like to create a PR for this?

Your solution:

```C
CGLM_INLINE
bool
glm_aabb_sphere(vec3 box[2], vec4 s) {
  float dmin = 0.f;
  int     i;

  for (i = 0; i < 3; ++i) {
    dmin += (s[i] < box[0][i] || s[i] > box[1][i])
                    ? glm_pow2(s[i] - box[s[i] > box[1][i]][i]) : 0;
  }

  return dmin <= glm_pow2(s[3]);
}
```
Alternative solution could be:

```C
CGLM_INLINE
bool
glm_aabb_sphere(vec3 box[2], vec4 s) {
  float dmin;
  int   a, b, c;

  a = s[0] < box[0][0] + s[0] > box[1][0];
  b = s[1] < box[0][1] + s[1] > box[1][1];
  c = s[2] < box[0][2] + s[2] > box[1][2];

  dmin  = glm_pow2((s[0] - box[!(a - 1)][0]) * (a != 0))
        + glm_pow2((s[1] - box[!(b - 1)][1]) * (b != 0))
        + glm_pow2((s[2] - box[!(c - 1)][2]) * (c != 0));

  return dmin <= glm_pow2(s[3]);
}
```

I'm not sure which one is faster. There may be redundant multiplications in the second solution but they could be eliminated.

**Comment by ILeonor** [comment]
Hi @recp 
Your solution is faster in most situations :)

tested on 10кк iterations:
your solution, sphere in box: 1039945 microseconds
my solution, sphere in box: 929294 microseconds
your solution, sphere intersect box 1053339 microseconds
my solution, sphere intersect box 1361337 microseconds
your solution, sphere no intersect box 1037820 microseconds
my solution, sphere no intersect box 1560051 microseconds

but there is an error in the calculation a, b, c. Correct:
```
a = (s[0] < box[0][0]) + (s[0] > box[1][0]);
b = (s[1] < box[0][1]) + (s[1] > box[1][1]);
c = (s[2] < box[0][2]) + (s[2] > box[1][2]);
```

**Comment by recp** [comment]
@ILeonor thanks for the benchmark 🤗

> but there is an error in the calculation a, b, c. Correct:

better in this way 👍

Would you like to create a PR for the fix/improvement? Otherwise I'll do it

**Comment by ILeonor** [comment]
@recp better if you do it

**Comment by recp** [comment]
@ILeonor sure, follow https://github.com/recp/cglm/pull/180
