### ISSUE TITLE
Provide a CMake interface library target

### ISSUE THREAD

**Issue by legends2k** [recp/cglm#181]
Applications using cglm as a pure header library currently do

``` cmake
add_subdirectory(external/cglm)
target_link_libraries(MyExecutable PRIVATE cglm)
```

However, this build `.c` files under `src/` only to be thrown away since the project isn't using the compiled _call_ variant of cglm i.e. `glmc_` functions aren't used but still they're built.

Providing an interface library target and a shared library target would give freedom for users to choose the right dependency level.

**Refer**: [Creating a header-only library with CMake](http://www.mariobadr.com/creating-a-header-only-library-with-cmake.html)

**Comment by recp** [comment]
@legends2k thaks for your feedbacks, you are right, we should not force users to build **cglm** if they only use headers.

Any PR would be appreciated ☺️ Otherwise I'll try to do it in my free time...

**Comment by legends2k** [comment]
My understanding of CMake is slim.  Nevertheless I'll raise a PR, please do correct me if I'm doing the wrong thing.

**Comment by recp** [comment]
see https://github.com/recp/cglm/pull/183
