### ISSUE TITLE
glm_mat4_print issue on FreeBSD

### ISSUE THREAD

**Issue by lliendo** [recp/cglm#185]
Hi there,

I don't really know if this is a bug or not (I'm going to assume that I'm probably missing something, if that's the case my apologies!). I'm trying to print a `mat4` data type through the `glm_mat4_print` function. I've already included both the `cglm/cglm.h` and the `cglm/io.h` headers where the function is being called. I'm getting no compiling errors at all and tried to print to both `stderr` and `stdout` without luck (`printf` is working absolutely fine). I'm using cglm in FreeBSD 12.2-RELEASE and the reported library version from pkg is: `cglm-0.7.9`. I have also searched through the cglm documentation PDF (version 0.8.1) for occurrences for the `glm_mat4_print` function, though I couldn't spot anything unusual. I've also tried to get the PDF documentation for version 0.7.9 but I can't find it (I wanted to see if there was something radically different for that version that prevents `glm_mat4_print` to correctly work).

Thanks in advance,
Lucas.

**Comment by recp** [comment]
Hi @lliendo 

Thaks for reporting this, and testing/using **cglm** on FreeBSD 

a note top of `io.h`

```C
/*
 cglm tried to enable print functions in debug mode and disable them in
 release/production mode to eliminate printing costs.
 
 if you need to force enable then define CGLM_DEFINE_PRINTS macro not DEBUG one
 
 Print functions are enabled if:
 
 - DEBUG or _DEBUG macro is defined (mostly defined automatically in debugging)
 - CGLM_DEFINE_PRINTS macro is defined including release/production
   which makes enabled printing always
 - glmc_ calls for io are always prints

 */
```

Also documented in:
https://cglm.readthedocs.io/en/latest/io.html
https://cglm.readthedocs.io/en/latest/opt.html

we may imporve documentation later.

**Comment by lliendo** [comment]
Thanks a lot for your fast reply and my apologies for not spotting: `Inline prints are only enabled in DEBUG mode and if CGLM_DEFINE_PRINTS is defined.`
