### ISSUE TITLE
build cglm for use in vulkan project

### ISSUE THREAD

**Issue by RoOddball** [recp/cglm#187]
hello, I am following the tutorial one of them for found so far https://vulkan-tutorial.com/en/Vertex_buffers/Vertex_input_description

and so i downloaded the cglm github project and tried to run the  build.bat file but it says htat msbuild is not a recognized command. This is a reall noob question I'm sure but just to be sure is it viable to try and use this to dynamically pass verteces to the pipeline ?

**Comment by recp** [comment]
Hi @RoOddball 

Yes **msbuild** must b installed on Windows before run `build.bat`, AFAIK, it comes with Visual Studio. You can also build with CMake if you want.

**Comment by recp** [comment]
Also you dont need to build **cglm** if you only use inline vesions e.g `glm_`.

Documentation:

https://cglm.readthedocs.io/en/latest/build.html

**cglm** provides

- inline api `glm_`
- call api `glmc_` *you need to build cglm first*
- struct api `glms_`
- Raw SIMD api `glmm_` *most part of **cglm** alreadt use SIMD

**Comment by recp** [comment]
Is this still valid?

**Comment by RoOddball** [comment]
Hey,
No it is not, that problem is solved. I didn’t expect you guys to be so
thorough, hats off and sorry
Andrei

**Comment by recp** [comment]
@RoOddball thanks 🤗🚀
