### ISSUE TITLE
Proposal, Optional: Omit `glm[s]` pefix in INLINE function names as an OPTION, especially fo struct api?

### ISSUE THREAD

**Issue by recp** [recp/cglm#197]
Since struct api is inline, we can provide an option to omit `glms_` name space?

```Swift
/* 1. struct api */

/* existing api; omit_ns is not defined */
return glms_vec3_normalize(glms_vec3_cross(a, b));

/* Optional */

#define CGLM_OMIT_NS_FROM_STRUCT_API

/* Option 1 */
return vec3_normalized(vec3_cross(a, b));

/* Option 2: `s` suffix stands for `struct` */
return vec3s_normalized(vec3s_cross(a, b));


/* 2. array api */
?
```

array api may remain same.

**Comment by iddev5** [comment]
Sounds great but is the goal of this change to make struct-based API more familiar-able(?)?
Is it complete omitting of old functions or just a layer/macro on top of existing?

**Comment by recp** [comment]
@iddev5 thanks for feedbacks,

> Is it complete omitting of old functions

No, if `#define CGLM_OMIT_NS_FROM_STRUCT_API` is defined some users may omit `glms_` prefix if they want. We can do this by surround functions by a macro (which may decrease readability of struct api headers) and omit glms_ namespace if `CGLM_OMIT_NS_FROM_STRUCT_API` is defined. 

Array api is similar to assembly, for instance:

```Swift
glm_mat4_mul(a, b, result);
glm_mat4_mulv(result, v, result_vec);
```

which looks cool, every functions has its own line, but struct api comes with `glms_` prefix:

```Swift
result_vec = glms_mat4_mulv(glms_mat4_mul(a, b), v);
```

which can be written as:

```Swift
#define CGLM_OMIT_NS_FROM_STRUCT_AP

result_vec = mat4_mulv(mat4_mulv(a, b), v);

/* or */
result_vec = mat4s_mulv(mat4s_mulv(a, b), v);
```

I'm not sure of course, we can ignore this proposal since it is just proposal for now.

**Comment by iddev5** [comment]
> surround functions by a macro
Okay, got it. I use the struct based API throughout all my projects. I do not really mind the presence of glms_ prefix. So this change is kind-of neutral to me.

**Comment by recp** [comment]
@iddev5 thanks for feedbacks, I'll keep this on hold until got enough feedbacks 👍

**Comment by recp** [comment]
A PR is created for the proposal: https://github.com/recp/cglm/pull/290

**Comment by recp** [comment]
Since https://github.com/recp/cglm/pull/290 has implemented this I'm going to close this.
