### ISSUE TITLE
cglm/struct/cam.h:68:14: error: 'clipspace/ortho_rh_no.h' file not found

### ISSUE THREAD

**Issue by hartenfels** [recp/cglm#200]
The latest pull request appears to have broken the struct API as described in the title:

```
/usr/local/include/cglm/struct/cam.h:68:14: error: 'clipspace/ortho_rh_no.h' file not found [clang-diagnostic-error]
#    include "clipspace/ortho_rh_no.h"
             ^
```

Looks like ~~it should be `../clipspace/ortho_rh_no.h`~~ the autoconf build doesn't install these new files properly. I'll probably provide a pull request fixing this in a bit.

**Comment by recp** [comment]
> I'll probably provide a pull request fixing this in a bit.

@hartenfels that would be great 🤗
