### ISSUE TITLE
glmc_vec4_scale_as header mismatch

### ISSUE THREAD

**Issue by YourWishes** [recp/cglm#213]
GCC is giving me compiler warnings that seem to stem from the header definition of `glmc_vec4_scale_as` being defined as;
`glmc_vec4_scale_as(vec3 v, float s, vec3 dest);`
but the method definition is set to;
`glmc_vec4_scale_as(vec4 v, float s, vec4 dest)`

Not sure if the vec3 in the header is correct, or the method definition is correct, but I assume that the vec4 scale would be preferred.

**Comment by recp** [comment]
Hi @YourWishes 

> glmc_vec4_scale_as(vec4 v, float s, vec4 dest)

is correct, the function creates new vector by scaling existing **vec4** as given scale factor.

A PR would be awesome if you would like to help, otherwise I'll fix it asap.

**Comment by YourWishes** [comment]
@recp Thanks, my bad on this one as I was using a version from a while ago and this has been fixed, closing issue.

Fixed in https://github.com/recp/cglm/pull/192/commits/13269f4af8d3c95220f97746c968eac3ba122a32#diff-f3e960d159809f4eac06da27686b9a6810a666ced007315ba59ed5101c3345caR102

**Comment by recp** [comment]
@YourWishes thanks 🤗
