### ISSUE TITLE
Add explicit complex type or complex number support in `vec2-ext`

### ISSUE THREAD

**Issue by mxi** [recp/cglm#227]
I implemented the Newton-Raphson root finder visualizer with the help of cglm for some view transformations. To my surprise during development, I wasn't able to find any complex number routines in cglm and had to write a poor man's implementation. 

I imagine the argument would be to simply use versors with the `j` and `k` components set to zero, but it's a bit messy jumping between `mat4`/`vec3` and `mat2`/`mat3`/`vec2`.

Would there be any objections to implementing some routines like complex multiplication, division, etc. in `vec2-ext`? I can take that on given a few days to adjust to the codebase a bit more, but I want to make sure my work isn't wasted.

Related: #173

Thanks,
Average cglm enjoyer

**Comment by recp** [comment]
Hi @mxi , sorry to the delay,

We can consider to support complex numbers if it is worth it,

> I can take that on given a few days to adjust to the codebase a bit more, but I want to make sure my work isn't wasted.

Did you implement complex numbers in your local branch?

Thanks

**Comment by mxi** [comment]
> Did you implement complex numbers in your local branch?

Did just now (#229).

**Comment by recp** [comment]
That PR is merged, thanks 🚀
