### ISSUE TITLE
Missing unions

### ISSUE THREAD

**Issue by awsdert** [recp/cglm#235]
Went to use ivec2s only to find it's not defined, please add it and any remaining structs using something like this:
```
#ifndef CGLM_IVEC2S_DEFINED
#define CGLM_IVEC2S_DEFINED
typedef union ivec2s {
  ivec2 raw;
#if CGLM_USE_ANONYMOUS_STRUCT
  struct {
    int x;
    int y;
  };
  struct
  {
    int r;
    int i;
  };
#endif
} ivec2s;
#endif
```
With this method code compiled against older variants of cglm (you know how linux distros can be) will be able to gracefully supplement their own implementation should the expected union not be found

**Edit:** Forgot to add r & i axis for real & "imaginary" numbers so just added them in now

**Comment by recp** [comment]
Hi @awsdert ,

Thanks for your feedback, just created a PR for this request: https://github.com/recp/cglm/pull/236

**Comment by recp** [comment]
@awsdert that PR is merged now, many thanks 🚀

**Comment by awsdert** [comment]
good 2 know, now I just need to wait for it to show up in the AUR, got it installed via there instead of keeping a portable copy
