### ISSUE TITLE
Error in glm_pickmatrix() arguments type

### ISSUE THREAD

**Issue by pm4gh** [recp/cglm#240]
glm_pickmatrix() is defined as:
`glm_pickmatrix(vec3 center, vec2 size, vec4 vp, mat4 dest)`
but center should be a vec2.

Noticed when building with gcc12 that gives this warning:
> src/project.c: In function 'glmc_pickmatrix':
src/project.c:32:3: warning: 'glm_pickmatrix' accessing 12 bytes in a region of size 8 [-Wstringop-overflow=]
   32 |   glm_pickmatrix(center, size, vp, dest);
        |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/project.c:32:3: note: referencing argument 1 of type 'float[3]'
src/project.c:32:3: note: referencing argument 2 of type 'float[2]'
src/project.c:32:3: note: referencing argument 3 of type 'float[4]'
src/project.c:32:3: note: referencing argument 4 of type 'float[4][4]'
In file included from src/../include/cglm/cglm.h:28,
                 from src/project.c:8:
src/../include/cglm/project.h:127:1: note: in a call to function 'glm_pickmatrix'
  127 | glm_pickmatrix(vec3 center, vec2 size, vec4 vp, mat4 dest) {
         | ^~~~~~~~~~~~~~

**Comment by recp** [comment]
Hi @pm4gh 

Many thanks for reporting this. This is fixed at https://github.com/recp/cglm/commit/2a4748d45265434b095714f185b40b22d76fc7f1

Let us know (with issues or with pull request) if any other error / warnings occurs. 

Thanks.
