### ISSUE TITLE
Add basic ivec functions

### ISSUE THREAD

**Issue by Chris-F5** [recp/cglm#248]
I'm working on a project in which I use a lot of **cglm**'s ivec types. I don't require all the functions that the floating point vec types have, but basic ivec functions would save me from (for example) using 3 lines of code just to copy an ivec3:
```
new_ivec3[0] = old_ivec3[0];
new_ivec3[1] = old_ivec3[1];
new_ivec3[2] = old_ivec3[2];
```
The functions I propose are:
```
void glm_ivec2(int* v, ivec2 dest)
void glm_ivec2_copy(ivec2 a, ivec2 dest)
void glm_ivec2_zero(ivec2 v)
void glm_ivec2_one(ivec2 v)
void glm_ivec2_add(ivec2 a, ivec2 b, ivec2 dest)
void glm_ivec2_adds(ivec2 v, int s, ivec2 dest)
void glm_ivec2_sub(ivec2 a, ivec2 b, ivec2 dest)
void glm_ivec2_subs(ivec2 v, int s, ivec2 dest)
void glm_ivec2_mul(ivec2 a, ivec2 b, ivec2 dest)
void glm_ivec2_scale(ivec2 v, int s, ivec2 dest)
int glm_ivec2_distance2(ivec2 a, ivec2 b)
float glm_ivec2_distance(ivec2 a, ivec2 b)
void glm_ivec2_maxv(ivec2 a, ivec2 b, ivec2 dest)
void glm_ivec2_minv(ivec2 a, ivec2 b, ivec2 dest)
void glm_ivec2_clamp(ivec2 v, int minVal, int maxVal) /* inclusive max and min */
+ corresponding ivec3 and ivec4 functions
```
Note that `glm_ivecn_distance2` returns int whereas `glm_ivecn_distance` returns float. Also, `glm_ivecn_clamp` is inclusive.

I would be happy to (try to) make these changes - just give me the green light.

**Comment by Chris-F5** [comment]
Great, I will begin working on this.

**Comment by recp** [comment]
That PR is merged, may thanks @Chris-F5 🚀
