### ISSUE TITLE
Black screen when using glm_lookat

### ISSUE THREAD

**Issue by RadoslavL** [recp/cglm#252]
I am sorry for creating this issue, but I've been trying to make this code work for so long! I made model, view and proj be identity matrices and then I ran `glm_lookat((vec3){0.0f, 0.0f, -4.0f}, (vec3){0.0f, 0.0f, 0.0f}, (vec3){0.0f, 1.0f, 0.0f}, view);` to set the view matrix and then I made the projection matrix work by using `glm_perspective(glm_rad(45.0f), (float)(width/height), 0.1f, 100.0f, proj);`. Everything seems like it should work, but then I pass the uniform values to the shader using:
```
glUniformMatrix4fv(modelloc, 1, GL_FALSE, &model[0][0]);
glUniformMatrix4fv(viewloc, 1, GL_FALSE, &view[0][0]);
glUniformMatrix4fv(projloc, 1, GL_FALSE, &proj[0][0]);
```
It just shows a black screen. I have no idea what to try next. Full sources - [https://pastebin.com/4vTzi2Dz](https://pastebin.com/4vTzi2Dz).

**Comment by recp** [comment]
Hi @RadoslavL ,

Sorry for the late response, I didn't see this issue somehow,

Have you tried to render the model without model, view and/or proj matrices (by ignoring multiplication with position vector) to see what is wrong shader, mvp matrix or something else

Thanks for sharing the source codes, I'll try to see what is wrong,

There is no (and should not) room for bugs in **cglm**  ;)

**Comment by RadoslavL** [comment]
If I comment out the `glm_lookat();` and `glm_perspective();` lines and make the matrices be identity ones, it works fine. The issue happens when I uncomment the lines.

**Comment by recp** [comment]
@RadoslavL I just tried to check a little bit,

```C
const unsigned int width = 1054;
const unsigned int height = 1057;
```

you created the perspective matrix like this:

```C
glm_perspective(glm_rad(45.0f), (float)(width/height), 0.1f, 100.0f, proj);
```

but the result of 
```C
(float)(width/height)
```
 is zero since width < height and both are integer. Since aspect ratio is zero in your case you get wrong `proj` and the result of MVP matrix is also wrong (includes `inf` ...)

Instead you could cast like this `(float)width/height` both `(float)width/(float)height`. Both should work. Give a try.

**Comment by RadoslavL** [comment]
Thanks! That worked! I was so confused to why nothing was showing up!

**Comment by recp** [comment]
It seems the issue can be closed now 🚀 Feel free to bring any bugs by creating issues/PRs...
