### ISSUE TITLE
Adding a new function

### ISSUE THREAD

**Issue by RadoslavL** [recp/cglm#253]
I was about to create a pull request to add a new function, but I read your "CONTRIBUTING.md" file and wanted to ask for permission. The function I am talking about is `glm_vec3_muls`. There are `glm_vec3_adds`, `glm_vec3_subs` and `glm_vec3_divs` functions, but no `glm_vec3_muls` function. Was this intended?

**Comment by recp** [comment]
Hi @RadoslavL ,

Thanks for contributing to **cglm**,

`glm_vec3_scale(vec3 v, float s, vec3 dest)` exactly does what you are looking for. It could be easy to find it with `glm_vec3_muls()` name but it scales the vector and current name seems good to me. An alias could be fine but I'm not sure:

```C
CGLM_INLINE
void
glm_vec3_muls(vec3 v, float s, vec3 dest) {
  glm_vec3_scale(v, s, dest);
}
```

**Comment by RadoslavL** [comment]
Thanks for the reply! That is what I was looking for!
