### ISSUE TITLE
How to use ease/interpolation functions?

### ISSUE THREAD

**Issue by fuck-shithub** [recp/cglm#258]
So I ran into a situation where I wanted to do interpolation for some animation code in my OpenGL application. I imagined that maybe a math library already had this functionality, so I looked around and as it turns out the library I am using for OpenGL math, cglm, contains some ease functions. So I look in the include files and I see this in cglm/include/cglm/ease.h:

```c
CGLM_INLINE
float
glm_ease_linear(float t) {
  return t;
}
```

What is the point of this? Does this function actually do anything? To me it just looks like it will return the same thing you gave as input. WTF?
There are also spline and other ease functions, but I don't know how to use them. It seems really confusing. Does anyone know what they are used for, and if they can be used for calculating interpolation?

**Comment by recp** [comment]
Hi @fuck-shithub ,

It is identical to [glm/gtx/easing.inl](https://github.com/g-truc/glm/blob/b3f87720261d623986f164b2a7f6a0a938430271/glm/gtx/easing.inl). They work how easing functions works. 

In the given parameter `t` `glm_ease_linear()` will always give same value which is linear. For instance if you increase the time `t` will change linearly:

**time-t map**

```
time     t      eased
-----    ---    -------
0.0      0      glm_ease_linear(t) = 0
0.1      1      glm_ease_linear(t) = 1
0.2      2      glm_ease_linear(t) = 2
0.3      3      glm_ease_linear(t) = 3
0.4      4      glm_ease_linear(t) = 4
0.5      5      glm_ease_linear(t) = 5
...
1.0      10     glm_ease_linear(t) = 10

```

other ease functions may return different values for each `t` value. 

```C
CGLM_INLINE
float
glm_ease_linear(float t) {
  return t;
}
```

each ease function accepts `t` and returns eased value. This is why `glm_ease_linear()` returns `t` without modifying it. You may change ease function dynamically at runtime in this case this function helps to provide linear ease function.

hope it helps.
