### ISSUE TITLE
absolute functions

### ISSUE THREAD

**Issue by duarm** [recp/cglm#261]
are we up to adding absolute functions for every vector type? quite useful for some algorithms

something like 
```c
void glm_vec2_abs(vec2 v)
{
	v[0] = fabs(v[0]);
	v[1] = fabs(v[1]);
}

**Comment by duarm** [comment]
just noticed there's already an undocumented abs function for vec3 only. https://github.com/recp/cglm/blob/master/src/vec3.c#L399

I'll add it to the docs too.

**Comment by recp** [comment]
> I'll add it to the docs. There are some others missing too like fract, shall we add them too? in another PR perhaps?

That would be awesome 🤗
