### ISSUE TITLE
assertion in test_clamp on x86

### ISSUE THREAD

**Issue by bl4ckb0ne** [recp/cglm#266]
Im (re) packaging cglm for Alpinelinux [1], and one of the test fails on x86 [2]

```
 assert fail in ../test/src/test_clamp.c on line 16 :  ASSERT(glm_clamp(0.6f, 0.0f, 1.0f) == 0.6f)
  𐄂 clamp 
```

Seems to be related to https://github.com/recp/cglm/issues/220, I'll poke around with various `GLM_FLT_EPSILON` values to see if it works.
 
[1]: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/41901
[2]: https://gitlab.alpinelinux.org/bl4ckb0ne/aports/-/jobs/916081

**Comment by recp** [comment]
Hi @bl4ckb0ne,

Sorry for the late response and thanks for the efforts to pack **cglm** on Alpinelinux,

yes it is better to use `glm_eq()` instead of `==` to compare floats due to floating errors.

**Comment by recp** [comment]
I have just updated that with https://github.com/recp/cglm/commit/ac9461778c8dbf5de3e04cd12b39f55228fa382c 

Can you check again pls.
