### ISSUE TITLE
NEON literal assignment

### ISSUE THREAD

**Issue by gottfriedleibniz** [recp/cglm#278]
Hi,

There are a few instances of direct literal assignment of float32x4_t's that will not compile w/ MSVCs Arm64 NEON declarations (does not support GCC/clang-style vector extensions; reference [this example](https://godbolt.org/z/rnb87GT1c)):

- [mat4.h#L111](https://github.com/recp/cglm/tree/bc8dc72739e4adec2a730792800dc82a2ff9f17d/include/cglm/simd/neon/mat4.h#L111)
- [mat4.h#L184](https://github.com/recp/cglm/tree/bc8dc72739e4adec2a730792800dc82a2ff9f17d/include/cglm/simd/neon/mat4.h#L184)
- [quat.h#L26](https://github.com/recp/cglm/tree/bc8dc72739e4adec2a730792800dc82a2ff9f17d/include/cglm/simd/neon/quat.h#L26)

While, MSC does not define [\_\_ARM_NEON](https://github.com/recp/cglm/blob/master/include/cglm/simd/intrin.h#L66-L68) nor __ARM_NEON_FP by default. The above statements seem to be the only thing preventing its use under MSVC Arm64.

**Comment by recp** [comment]
Hi @gottfriedleibniz,

Sorry for the delay, I just saw the issue. 

> MSC does not define [__ARM_NEON](https://github.com/recp/cglm/blob/master/include/cglm/simd/intrin.h#L66-L68) nor __ARM_NEON_FP by default

Wow, I'll investigate NEON on MSVC asap, any suggestions?

**Comment by recp** [comment]
@gottfriedleibniz can you check (and test if possible) https://github.com/recp/cglm/issues/278 PR. Any feedbacks would help a lot, thanks

**Comment by recp** [comment]
It uses `glmm_float32x4_init()` macro to init float32x4 on neon. 

Definition: 

```C
#if defined(_WIN32) && defined(_MSC_VER)
#  define glmm_float32x4_init(x, y, z, w) { .n128_f32 = { x, y, z, w } }
#else
#  define glmm_float32x4_init(x, y, z, w) { x, y, z, w }
#endif
```

and usage:

```C
/* glm_mat4_det_neon() line 111: */
float32x4_t   x3 = glmm_float32x4_init(0.f, -0.f, 0.f, -0.f);
```
