### ISSUE TITLE
Bug in glm_mat4_print?

### ISSUE THREAD

**Issue by deadwanderer** [recp/cglm#288]
In `glm_mat4_print()` in `io.h`, it appears that row and column get switched when printing out the matrix.
(https://github.com/recp/cglm/blob/1d51459a4f76a936a985fa1ba5bacf1d19095d1c/include/cglm/io.h#L87-L97)
```
for (i = 0; i < m; i++) {
    fprintf(ostream, "  |");

    for (j = 0; j < n; j++)
      if (matrix[i][j] < CGLM_PRINT_MAX_TO_SHORT)
        fprintf(ostream, " % *.*f", cw[j], CGLM_PRINT_PRECISION,
                (double)matrix[j][i]);
      else
        fprintf(ostream, " % *g", cw[j], (double)matrix[j][i]);

    fprintf(ostream, "  |\n");
  }
```

Shouldn't the matrix[j][i] accesses here be matrix[i][j]? Every other access in this function has been matrix[i][j], and it makes the matrix print out transposed.

**Comment by deadwanderer** [comment]
This same behavior occurs in `glm_mat3_print` and `glm_mat2_print`, if it is a bug. I'm more than happy to provide a PR.

**Comment by recp** [comment]
Hi @deadwanderer,

Thanks for the feedbacks,

**cglm** uses column-major layout as stated in documentation/README. An option could be provided to support row-major maybe in the future. 

In this case to print matrix elements we need to access them through `matrix[j][i]` to make it readable by humans. Here:

```
m00    m10    m20    m30           <---  print this line first 
m01    m11    m21    m31           <---  then
m02    m12    m22    m32           <---  then
m03    m13    m23    m33           <---  then
```

hope it helps
