### ISSUE TITLE
0.9 build failure on arch other than x86_64 and aarch

### ISSUE THREAD

**Issue by bl4ckb0ne** [recp/cglm#296]
Im getting the following error when building 0.9.0 on arch other than x86_64 and aarch in the alpine linux CI [1]

```
ninja: job failed: gcc -Ilibcglm.so.0.9.0.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -Os -Wformat -Werror=format-security -Os -Wformat -Werror=format-security -fPIC -MD -MQ libcglm.so.0.9.0.p/src_io.c.o -MF libcglm.so.0.9.0.p/src_io.c.o.d -o libcglm.so.0.9.0.p/src_io.c.o -c ../src/io.c
In file included from ../src/../include/cglm/cglm.h:30,
                 from ../src/io.c:10:
../src/../include/cglm/io.h: In function 'glm_arch_print_name':
../src/../include/cglm/io.h:70:38: error: unused parameter 'ostream' [-Werror=unused-parameter]
   70 | glm_arch_print_name(FILE* __restrict ostream) {
      |            
```

[1]: https://gitlab.alpinelinux.org/alpine/aports/-/pipelines/162977

**Comment by recp** [comment]
Hi @bl4ckb0ne,

Thanks for reporting this,

https://github.com/recp/cglm/commit/ed09fb5819615f2178d7d4bf97ba133c4ee7e3f3 commit should fix this, can you give a try pls?

**Comment by bl4ckb0ne** [comment]
Had to pull 2d6538ecec7e6dbedb379f11b366e3051267e995 to fix a compilation issue but it seems to be working. Sorry to answer that late and thanks a lot!
