### ISSUE TITLE
CGLM_OMIT_NS_FROM_STRUCT_API breaks compilation

### ISSUE THREAD

**Issue by FrostKiwi** [recp/cglm#314]
I want to switch my project over to the struct API, but fail to compile when specifying `CGLM_OMIT_NS_FROM_STRUCT_API` in addition to `#include "cglm/struct.h"`.
```console
In file included from inc/cglm/struct.h:25:
inc/cglm/struct/box.h:36:3: error: call to undeclared function 'glms_vec3_pack'; ISO C99 and
      later do not support implicit function declarations [-Wimplicit-function-declaration]
  glms_vec3_pack(dest, rawDest, 2);
```
<details><summary>Version of emscripten/emsdk</summary>

```console
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.38 (9eff02bc816c50ab0e3b70a3bd5b72a8dc2893a2)
clang version 17.0.0 (https://github.com/llvm/llvm-project 004bf170c6cbaa049601bcf92f86a9459aec2dc2)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\<redacted>\min\home\artsimow\build\emsdk\upstream\bin
```
</details>

**Comment by recp** [comment]
Hi @FrostKiwi,

https://github.com/recp/cglm/commit/adec2ee8e6679efec4c85aa8f6c9afe567a686c1 should fix this,

thanks for reporting the issue

**Comment by FrostKiwi** [comment]
Compiled successfully and works now.

**Comment by FrostKiwi** [comment]
Not sure how I feel about somethings not having `glms_` removed and thus having a mix of both, like `glms_translate()` not becoming `translate()` I guess this is to avoid collisions?

**Comment by recp** [comment]
Yes to avoid collisions I kept glms for root namespace. Another option like `CGLM_OMIT_ROOTNS_FROM_STRUCT_API` could be added for who want to remove `glms_` from `glms_translate()` like functions maybe.
