### ISSUE TITLE
Struct API missing 3D Affine Transform

### ISSUE THREAD

**Issue by FrostKiwi** [recp/cglm#316]
I found both...
https://github.com/recp/cglm/blob/adec2ee8e6679efec4c85aa8f6c9afe567a686c1/include/cglm/affine-mat.h#L115
https://github.com/recp/cglm/blob/adec2ee8e6679efec4c85aa8f6c9afe567a686c1/include/cglm/affine-mat.h#L166
...to be very useful optimizations and use them in my camera calculation code. I recently switched to the struct API and found them to be missing, requiring me to use
```c
glm_mul_rot(gctx.cam.view_matrix.raw, gctx.cam.cam_rotation_matrix.raw,
	gctx.cam.view_matrix.raw);
glm_inv_tr(gctx.cam.view_matrix.raw);
```
Would be really nice if they could be added to the struct api.

**Comment by recp** [comment]
Wow yes indeed we should add them to struct api (*affine-mat.h*), a PR would be nice to bring these to struct api otherwise I'll do asap :)

**Comment by FrostKiwi** [comment]
> Wow yes indeed we should add them to struct api (_affine-mat.h_), a PR would be nice to bring these to struct api otherwise I'll do asap :)

Kinda hacked it into my codebase already. I'll make a PR later this evening.

**Comment by recp** [comment]
@FrostKiwi thanks 🤗

**Comment by FrostKiwi** [comment]
> @FrostKiwi thanks 🤗

@recp added in PR https://github.com/recp/cglm/pull/317
