### ISSUE TITLE
`glms_vec4_inv` does not actually exist

### ISSUE THREAD

**Issue by v1993** [recp/cglm#358]
https://github.com/recp/cglm/blob/c6e58bd44aff1d132f79279a31cb9e247c98d277/include/cglm/struct/vec4.h#L45

This function is nowhere to be found in file.

**Comment by recp** [comment]
Hi @v1993,

Good catch! `glm_vec4_inv()` is deprecated in favor of `glms_vec4_negate()` this is why there is no struct version, we should remove that from comment/list. 

Done, see: https://github.com/recp/cglm/commit/1fdc1c86757f50438434528ecddd62e41940e41d 

Feel free to bring any other issues if there are any.
