### ISSUE TITLE
(feature request) mulsub functions

### ISSUE THREAD

**Issue by BeeverFeever** [recp/cglm#363]
Feature request for functions like the muladd functions but for subtraction instead.

So for example `glm_vec3_subsub(a, b, d)` would do `d -= (a - b)`.

I'm not sure if there is a reason these aren't already functions in the library but I feel like they would be really useful (well they would be for me right now).

I would be happy to work on implementing them if it is something that is wanted.

**Comment by recp** [comment]
Hi @BeeverFeever,

Since we have _addadd, _addsub, _muladd we could also have `_subsub` 👍

> I would be happy to work on implementing them if it is something that is wanted.

Sure, I'll wait a PR then, thanks
