### ISSUE TITLE
`glms_project_z` missing

### ISSUE THREAD

**Issue by v1993** [recp/cglm#365]
I've noticed that `glms_project_z` function is missing from `cglm/struct/projection.h`; ZO/NO-specific versions are declared in appropriate files, however. Seems to be an oversight?

**Comment by recp** [comment]
Hi @v1993,

We should add `glms_project_z()` which is forgotten to be added, 

Thanks for the catch

**Comment by recp** [comment]
@v1993 https://github.com/recp/cglm/commit/3b1d4fc5465237a8fba46e58739a810ed5fcb091 commit addresses the issue. 

Thanks for your contributions ☺️
