### ISSUE TITLE
`struct/clipspace/project_*.h` headers are broken

### ISSUE THREAD

**Issue by v1993** [recp/cglm#366]
Issues with them:

1. Do not include corresponding array headers
2. Have `dest` argument, resulting in redeclaration
3. `glms_project_z_*` has return type `vec3s` instead of expected `float`

**Comment by v1993** [comment]
Problem 1 seems to happen with *all* struct clipspace headers - none of them include corresponding array API headers, resulting in errors if those headers are not included as a side effect.

**Comment by recp** [comment]
Hi @v1993,

You seems to be correct, we need fix them asap

Any time to fix them or I'll do it asap?
