### ISSUE TITLE
`glms_rotate_atm` has wrong signature

### ISSUE THREAD

**Issue by v1993** [recp/cglm#368]
https://github.com/recp/cglm/blob/05d45872a3da42b85f4e8a10dfb40b5e37205046/include/cglm/struct/affine.h#L136

It makes no sense to accept matrix as the first argument, since this function initializes it.

**Comment by recp** [comment]
Hi @v1993,

You are correct `m` is **dest** in array api, we dont need it in struct since we can alloc and return it.

We can drop it

**Comment by recp** [comment]
@v1993 https://github.com/recp/cglm/commit/5be1c2f0599b4feab049ba677edf4e41c2c7c6a7 addresses the issue.
