### ISSUE TITLE
Should there be a dot product for integer vectors?

### ISSUE THREAD

**Issue by vitassuper** [recp/cglm#380]
I found that the dot product function is implemented only in the `vec2.h `header. Should there be a corresponding function glm_ivec2_dot in the `ivec2.h` header?

**Comment by recp** [comment]
Hi @vitassuper,

Yes that can be, all vector families can have dot product function. A PR that implement this would be appreciated, otherwise I'll add TODOs and implement it in an available time.

**Comment by vitassuper** [comment]
> Hi @vitassuper,
> 
> Yes that can be, all vector families can have dot product function. A PR that implement this would be appreciated, otherwise I'll add TODOs and implement it in an available time.

I will create a PR

**Comment by vitassuper** [comment]
I created a pull request that adds a dot function, along with several other functions, for `ivec2` and `ivec3`. #381

**Comment by recp** [comment]
@vitassuper thanks the PR is merged 👍
