### ISSUE TITLE
Struct API for ivec2s, ivec3s, and ivec4s

### ISSUE THREAD

**Issue by tarhses** [recp/cglm#382]
Hello,

I just started to use this lib and noticed that there aren't any struct API function counterparts of `glm_ivec2_*`, `glm_ivec3_*`, etc. Is this intentional?

I started implementing cglm/struct/ivec2.h on my side and would gladly contribute if welcome :smiley:

Anyway thanks for the hard work!

**Comment by recp** [comment]
Hi @tarhses,

This is discussed a bit here: https://github.com/recp/cglm/discussions/370#discussioncomment-7806749

> I started implementing cglm/struct/ivec2.h on my side and would gladly contribute if welcome 😃

That would be awesome! 

> Anyway thanks for the hard work!

Many thanks 😊

**Comment by recp** [comment]
@tarhses the PR is merged, many thanks for your contributions, we can close the issue now
