### ISSUE TITLE
msvc: formal parameter with requested alignment of 16 won't be aligned

### ISSUE THREAD

**Issue by recp** [recp/cglm#4]
``` C
typedef CGLM_ALIGN(16) float vec4[4];
```

according MSDN, functions params cannot be aligned by __declspec(align(16)) :/

https://msdn.microsoft.com/en-us/library/373ak2y1(v=VS.100).aspx

**Comment by recp** [comment]
Possible solution:

use `vec4 *` instead of `mat4` in function parameters, mat4 is will be decayed to vec4 * anyway

or  

disable align for msvc

**Comment by recp** [comment]
`vec4`and `mat4` requires 16 byte boundary aligment but msvc don't allow to align func params or alignment attrib in func params

So we can use `u` prefix or postfix to specify unaligned e.g. `umat4`, `uvec4`. Maybe to fix this issue we can convrt all params with `u` prefix e.g. 

`glm_mat4_mul(umat4 m1, umat4 m2, umat4 dest)`

instead of 

`glm_mat4_mul(mat4 m1, mat4 m2, mat4 dest)`

but aligned version of SIMD instructions need mat4, vec4 to be aligned. Does making func param unaligned affect this requirement? 
```C
mat4 m1, m2, m3; /* aligned */

glm_mat4_mul(umat4 m1, umat4 m2, umat4 dest) { ... } /* unaligned params */

/* alined version */
glm_mat4_mul(m1, m2, m3); /* use alignment optimized instructions e.g. _mm_load_ps */

```

**Comment by edelsohn** [comment]
This issue was proposed as a bounty for IBM.  While IBM is interested in SIMD optimizations of various math libraries, MSVC does not support the IBM PowerPC architecture.  The specific issue does not seem relevant.  And the interest in math libraries depends on the specific library and its usage.

**Comment by recp** [comment]
@edelsohn thanks for clarification

**Comment by recp** [comment]
Now alignment requirement is disabled for older visual studios, also it is optional now :https://github.com/recp/cglm/pull/53
