### ISSUE TITLE
cglm incorrectly assumes that SSE2 is also available when SSE1 is 

### ISSUE THREAD

**Issue by aryalaadi** [recp/cglm#401]
this causes builds for i686 to fail 

related [issue](https://github.com/void-linux/void-packages/pull/49348#issuecomment-2021864629)

**Comment by recp** [comment]
Hi @aryalaadi,

You are right we must check these separately. Actually most of existing operations are f32 which is supported by SSE. There are some exceptions like `_mm_castsi128_ps` and maybe more... We can check where SSE2 is not supported and fallback some intrinsics to SSE if possible.

Added to TODOs, but a PR would indeed bring the fix more quickly

**Comment by recp** [comment]
@aryalaadi I tried to fix the issue at https://github.com/recp/cglm/pull/412 any help, feedbacks would be awesome to make the work bug-less

**Comment by recp** [comment]
The issue is fixed at v0.9.4: https://github.com/recp/cglm/releases

Thanks for reporting this.
