### ISSUE TITLE
Visual Studio 2022 C17 Compiler unsafe sprintf error C4996

### ISSUE THREAD

**Issue by adotspooner** [recp/cglm#415]
Hi :) I get the following error with my project settings in Visual Studio 2022 with the C17 Compiler.
I would like to let this security warning feature enabled, maybe cglm could upgrade to the secure versions of the print functions?

```
Error C4996 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. 
To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
cglm-0.9.4\include\cglm\io.h	135
```

**Comment by adotspooner** [comment]
Hi @recp,

thank you for this ultra fast response, I will build cglm with this commit tomorrow and try it with my VS project.

**Comment by adotspooner** [comment]
Hi @recp, I tested my code with the build of the master branch at eb3a51e and I could remove the `_CRT_SECURE_NO_WARNINGS` without getting errors. Thank you again!

**Comment by recp** [comment]
@adotspooner great to hear that! 

Thanks
