### ISSUE TITLE
refract implementation

### ISSUE THREAD

**Issue by gottfriedleibniz** [recp/cglm#422]
Believe the [current](https://github.com/recp/cglm/commit/6ad0aca7e0609c91cf91868b9081a3cdd2652016#diff-52ea2009adee501f85d44386d87e3dd340d17ca2faa178ce25bd9a4fe2bb2564R749) refract implementation is mixing up the signs. Referencing GLSL: $`K = 1.0 - \mu^2 (1.0 - (N \boldsymbol{\cdot} I)^2)`$, which would imply `1.0f - eta * eta + eni * eni;` in code.

**Comment by recp** [comment]
Hi @gottfriedleibniz,

Sorry for the delay, thanks for the catch 🤗

https://github.com/recp/cglm/commit/48839a38a14a653c233693fa911348ce58d57167 should fix that
