### ISSUE TITLE
Inaccurate comments in include/cglm/vec3-ext.h

### ISSUE THREAD

**Issue by pm4gh** [recp/cglm#427]
The comment for glm_vec3_isnan() "@brief check if all items are NaN (not a number)" is wrong. The one for the same function in vec4-ext.h is better: "@brief check if one of items is NaN (not a number)"

There is a smilar error in glm_vec3_isinf().

**Comment by recp** [comment]
Hi @pm4gh,

Sorry for the delay, https://github.com/recp/cglm/commit/ad009d4e49b850c8cad2b3fb191c5a7b0fca9f2d makes the change. 

Thanks
