### ISSUE TITLE
glm_vec_distance2

### ISSUE THREAD

**Issue by winduptoy** [recp/cglm#60]
See documentation: http://cglm.readthedocs.io/en/latest/vec3.html#c.glm_vec_distance2

This function is missing in the source code. Is there any reason that it got removed? I think that having a non square-root function is handy for performance when sorting by distance or something, when exact distances are not needed.

**Comment by winduptoy** [comment]
Oops! I was running an old version of cglm! Sorry about that.

**Comment by recp** [comment]
Hi @winduptoy,

A new version have just been released 0.4.8: https://github.com/recp/cglm/releases/tag/v0.4.8
You may want to use that if you pull sources using tag.

There is a critical bugfix (alignment bug) for AVX in that release.

Actually we need more tests on new features. After implementing some features on my render engine, I will try to write more unit tests.

Best
