### ISSUE TITLE
Bug in vec2 implementation

### ISSUE THREAD

**Issue by brettridel** [recp/cglm#66]
I detected bugs in the implementations of some vec2 functions.
At the moment, there is at least **glm_normalize**, **glm_vec_normalize** and **glm_vec_norm**

It seems that there are no specialized vec2 functions, so the vec3 ones are utilized. Therefore, these functions uses unpredictable third coordinates instead of a z coordinate set to zero.

**Comment by recp** [comment]
Please follow this PR: https://github.com/recp/cglm/pull/97
