### ISSUE TITLE
Feedbacks for vec3 update

### ISSUE THREAD

**Issue by recp** [recp/cglm#67]
* Do we want to change `glm_vec_` namespace to `glm_vec3_`? 
* I want to rename `glm_vec_flipsign()` to `glm_vec_negate()` and deprecate `glm_vec_flipsign()` in favor of negate
* `glm_vec_inv()` inverts sign of components (same as negate) but probably it should invert vector components like glMatrix.js (https://github.com/toji/gl-matrix/blob/master/src/vec3.js#L321)? :

```C
CGLM_INLINE
void
glm_vec_inv_to(vec3 v, vec3 dest) {
  dest[0] = 1.0f / dest[0];
  dest[1] = 1.0f / dest[1];
  dest[2] = 1.0f / dest[2];
}
```
* it seems cglm should support **vec2** functions too ( #66  )

Any other feedback, bug or feature request? Or what do you think about these changes?

**Comment by stfx** [comment]
I thought about trying to integrate the library in a released game which requires high performance and not having vec2 functions is definitely a bit of a showstopper. Changing the vec3 namespace is probably needed afterwards to reduce confusion. Also having type safety with equal performance would definitely increase the accessibility/usability of this library.

**Comment by recp** [comment]
@stfx thanks for your feedback[s]. I'm glad to see that you have considered **cglm** to be used in your game. **vec2** was in my TODOs and still in TODOs :) 

I may work on it soon, after created a PR of **vec2**, feedbacks will be welcome especially from who uses **vec2** in their game, engine...

 if you need specific **vec2** features then please let me know by creating an issue or a Pull Request ;)

The namespace is already changed to **glm_vec3_** at https://github.com/recp/cglm/pull/68 and I think it is better now.

FWIW, I'll try to implement **vec2** and **mat2** in this weekend. Because I may need **vec2/mat2** in https://github.com/recp/ui project

To provide type safety, **cglm** may offer alternative API (optional) to use structs, see https://github.com/recp/cglm/issues/58.  if you have better idea for type safety (like compiler flag...) please let me know.

**Comment by recp** [comment]
Now we have **vec2** and **vec3** name space, thanks for all feedbacks which are always welcome!
