### ISSUE TITLE
error when running make check

### ISSUE THREAD

**Issue by vikke1234** [recp/cglm#69]
[test-suite.log](https://github.com/recp/cglm/files/2648917/test-suite.log)
attached error log

**Comment by recp** [comment]
Hi @vikke1234, thanks for sharing the test results. 

I guess comparing result like `m3[i][j] == 1.0f` is not good idea after float multiplication.
I replaced that with`glm_eq(m3[i][j], 1.0f)` and it should fix test.

Can please you pull master and check result again? 

Thanks

**Comment by vikke1234** [comment]
@recp I did that, still fails 
[test-suite.log](https://github.com/recp/cglm/files/2672284/test-suite.log)

**Comment by recp** [comment]
@vikke1234 thanks, what is your environment e.g operating system (with version), compiler, cpu... ? 

One another thing to do could be printing failed matrix before asserts, could you do that (test/src/test_mat3.c)? You can print matrix with `glm_mat3_print(m3, stderr);`, it uses %0.4f precision (probably not enough); you can change that for test or you can print matrix manually 

`glm_eq` uses **FLT_EPSILON**, maybe it is too small for comparing floats

**Comment by vikke1234** [comment]
@recp ubuntu 18.04, intel i5-8250U, I belive it used gcc to compile it, but I tried to print the matrix but didn't do anything. Also sorry for being slow at responding, I've been very busy the past few weeks.

**Comment by vikke1234** [comment]
@recp I ran the test on another computer same issue
[test-suite.log](https://github.com/recp/cglm/files/2706375/test-suite.log)

**Comment by recp** [comment]
I have run tests on Ubuntu VM, I got similar results (tests failed). But if I use volatile in loop variables then tests pass:

Before (`test/src/test_mat3.c`):
```C
  int i, j, k;

  /* test identity matrix multiplication */
  glmc_mat3_mul(m1, m2, m3);

  for (i = 0; i < 3; i++) {
    for (j = 0; j < 3; j++) {
      if (i == j) {
        assert_true(glm_eq(m3[i][j], 1.0f));
      } else {
        assert_true(glm_eq(m3[i][j], 0.0f));
      }
    }
  }
```

After:
```C
  volatile int i, j, k;

  /* test identity matrix multiplication */
  glmc_mat3_mul(m1, m2, m3);

  for (i = 0; i < 3; i++) {
    for (j = 0; j < 3; j++) {
      if (i == j) {
        assert_true(glm_eq(m3[i][j], 1.0f));
      } else {
        assert_true(glm_eq(m3[i][j], 0.0f));
      }
    }
  }
```

it is weird, somehow CPU caches **i** and/or **j** values and re-uses them instead of getting new value. 

This seems not true on macOS, it always passes, probably it uses clang, maybe using gcc would cause to get same result.

Any idea why CPU caches these values? I guess tests use single thread but not sure for this :/

**Comment by recp** [comment]
@vikke1234 built-in alignment is removed from vec3 and mat3 types, can you pull master branch and re-run tests for new changes?

**Comment by vikke1234** [comment]
@recp yeah, now it passes everything, thank you!
