### ISSUE TITLE
Compatibility with original glm

### ISSUE THREAD

**Issue by dkrikun** [recp/cglm#7]
Hello,

1. How feature-complete cglm is compared to glm?
2. Does cglm behave identically to glm (in the sense that the corresponding functions do the same thing as in glm)?

Thx

**Comment by recp** [comment]
> 1. How feature-complete cglm is compared to glm?

cglm is separate library, I've added features which I needed. 
Some features may not exist in cglm yet, but contributions are welcome 

Some operations are optimized manually some operations e.g. vec4, mat4...
optimized by SSE/AVX instructions. Also I'm going to optimize it with ARM Neon
This lib aimed best performance, readability and portability

Currently SSE operations required vec4 and mat4 aligned,
cglm will allow to work on unaligned memory too, I'll work on it asap.
for instance `glm_umat4_mul` `u` stands for unaligned

You can use cglm as header-only or pre-compiled 

I'll continue add features, feel free to create PR, report bug or suggest feature,

> 2. Does cglm behave identically to glm (in the sense that the corresponding functions do the same thing as in glm)?

I didn't copy-paste original glm codes except some special funcs for instance lookat
it should behave identically to glm if there is no bug in cglm or in glm.

If somethings is wrong please let me know, or any PR are welcome :)

**Comment by recp** [comment]
@dkrikun I've added some tasks to README about this
