### ISSUE TITLE
Does the library support Mac OS?

### ISSUE THREAD

**Issue by ccworld1000** [recp/cglm#73]
Does the library support Mac OS?

**Comment by recp** [comment]
Hi @ccworld1000 

Yes it does, macOS is my main development environment ;)  

Are there any issues or bugs about running on macOS?

**Comment by ccworld1000** [comment]
Thank you. I haven't seen the corresponding introduction for mac.

Can cocoapods import be supported?

Or I'll try it later.

**Comment by recp** [comment]
Check this issue: https://github.com/recp/cglm/issues/47

I was added **cglm** to Cocoapods and Homebrew, Homebrew formula is updated regularly but I did not update cocoapod recently :( You are welcome to update it or you can wait for me

**Comment by ccworld1000** [comment]
OK! I'm trying to deal with it, to see if there's a conflict.

**Comment by ccworld1000** [comment]
![5ce7e183-090a-486b-a7cd-754c342380d3](https://user-images.githubusercontent.com/22360168/51893928-59a35180-23e1-11e9-8161-dbf13c9209e9.png)

Seemingly privileged

**Comment by ccworld1000** [comment]
I want to make up for all the versions that are not available in the follow-up of the project.

**Comment by recp** [comment]
```bash
$ pod trunk add-owner cglm ccworld1000@gmail.com
  - Owners:
    - Recep Aslantas <recp@acm.org>
    - ai mac <ccworld1000@gmail.com>
```

**Comment by ccworld1000** [comment]
![8066969d-e7d6-4db6-9515-d3d523351dd0](https://user-images.githubusercontent.com/22360168/51895032-3332e580-23e4-11e9-9b8a-9013ec8a001a.png)
I'll deal with the rest.

**Comment by recp** [comment]
Perfect! Now we can close this issue, I guess?

**Comment by ccworld1000** [comment]
![b2557933-e65e-4992-8f03-6e38cac31054](https://user-images.githubusercontent.com/22360168/51896216-edc3e780-23e6-11e9-8f4e-194e909acb3c.png)

It is OK now
