### ISSUE TITLE
Crash Exception on VisualStudio2017

### ISSUE THREAD

**Issue by heitaoflower** [recp/cglm#75]
Hi my friend, I always encounter a issure like below. when I call something like
 `glm_translate(model->transforms[0], model->position);`

`glm_translate(mat4 m, vec3 v) {
#if defined( __SSE__ ) || defined( __SSE2__ )
  glmm_store(m[3],`

My compiler told me exception when access some address.

**Comment by recp** [comment]
Hi @heitaoflower,

There are some reasons you may get this or similar errors, crashes:

- Input or output parameters (`model->transforms[0]` and `model->position` in your case) may be **NULL**
- `vec4`, `versor` and `mat4` requires alignment (16 byte for vec4/versor, 32 byte for matrix if AVX enabled, if not then it only requires 16 byte alignment). If `model->transforms[0]` or `model->position` is not aligned then probably you will get crash.

To fix alignment issue:

- You have an option to disable alignment requirement for all types. To disable alignment define a macro called **CGLM_ALL_UNALIGNED** before include any cglm header. It is better to define this macro at project settings. Or if you want to define it in header, define it before including **cglm** headers:

```C
#define CGLM_ALL_UNALIGNED

#include <cglm/cglm.h>
```

If you want to use aligned versions then make sure all variables to pass cglm functions are aligned. If you use **cglm** types in your structs then probably those variables will be aligned if struct is not packed. 

To see all options: https://cglm.readthedocs.io/en/latest/opt.html

**Comment by heitaoflower** [comment]
It works now, Thank you very much for your explanation!
