### ISSUE TITLE
[Question] Why only vec3 in this particular line use CGLM_ALIGN(16) instead of CGLM_ALIGN(8)

### ISSUE THREAD

**Issue by haxpor** [recp/cglm#76]
I'm curious why this only [line](https://github.com/recp/cglm/blob/8fa21a1837783154589fbef2fc2a515aa5360946/include/cglm/affine-mat.h#L155) using `CGLM_ALIGN(16)` instead of `CGLM_ALIGN(8)` as the latter is used all across the board for all other vec3 declaration.

I probably miss and didn't have intuition about something here. But would love to understand this as now my wires to the following according to some studying at the cglm source code.

```
vec3 -> CGLM_ALIGN(8)
vec4 -> CGLM_ALIGN(16)
mat3 -> CGLM_ALIGN_MAT (depends on whether AVX is supported, 32 if support, 16 if not)
mat4 -> CGLM_ALIGN_MAT (depends on whether AVX is supported, 32 if support, 16 if not)
versor -> CGLM_ALIGN(16)
```

Thanks!

**Comment by recp** [comment]
Hi @haxpor,

`CGLM_ALIGN(8)` could be enough here, probably copy-paste error :) actually built-in alignment is removed from **vec3** and **mat3** types recently, so there is no strict requirement for alignment for vec3/mat3 anymore... 

In the future we may use SIMD to load/store **vec3** (e.g. by using [glmm_laod3](https://github.com/recp/cglm/blob/master/include/cglm/simd/x86.h#L118) or something else...) this requires vec3 to be aligned (8byte)

To load/store **mat3**, we use SIMD instructions which do not require alignment e.g. `_mm_loadu_ps` but according to resources even these instructions work faster if there is alignment (not sure for new CPUs)... so I would prefer to keep alignments in headers on local/temp variables.

**Comment by haxpor** [comment]
Alright! Thank you for detailed explanation, and great project.
