### ISSUE TITLE
error: undefined reference to 'vaddvq_f32'

### ISSUE THREAD

**Issue by haxpor** [recp/cglm#82]
I try to build cglm on two abis which are `armeabi-v7a` and `arm64-v8a` onto android device that is `aarch64`. I faced the problem shown with the error same as the title of this issue. Thus only `armeabi-v7a` cannot be built, the another is fine.

After initial digging it, I found this [line](https://github.com/recp/cglm/blob/81a74ba2255dd4c60f19126aab9d78609e74a5c8/include/cglm/vec4.h#L703) defined in `vector4.h`. It uses NEON function namely `vaddvq_f32` which is available only on armv8 (aarch64). I believe that this is not intention as for another place in which there is safety guard implemented in `arm.h` of these [lines](https://github.com/recp/cglm/blob/81a74ba2255dd4c60f19126aab9d78609e74a5c8/include/cglm/simd/arm.h#L19-L20).

Please correct me if I'm wrong, or might miss-understand. Anyway, if that's the opposite, I'm willing to do a PR on this (possibly add preprocessor guard + use NEON functions supported by `armeabi-v7a` instead) but please kindly guide me which NEON functions I should be using instead.

**Comment by recp** [comment]
Hi @haxpor 

A PR would be perfect 🤗 We could simply use `glmm_hadd` instead of using `vaddvq_f32` directly as you mentioned. 

`glmm_` is SIMD namespace and it helps to group and OPTIMIZE common tasks by arch, provide native SIMD api...

**Comment by recp** [comment]
Maybe we could use `glmm_dot`even `glmm_norm` like below:

```C
CGLM_INLINE
float
glm_vec4_distance(vec4 a, vec4 b) {
#if defined( __SSE__ ) || defined( __SSE2__ )
  return glmm_norm(_mm_sub_ps(glmm_load(b), glmm_load(a)));
#elif defined(CGLM_NEON_FP)
  return glmm_norm(vsubq_f32(glmm_load(a), glmm_load(b)));
#else
  return sqrtf(glm_pow2(b[0] - a[0])
             + glm_pow2(b[1] - a[1])
             + glm_pow2(b[2] - a[2])
             + glm_pow2(b[3] - a[3]));
#endif
}
```

`glmm_norm` uses optimized `glmm_hadd`.

Or we could simply use this:

```C
CGLM_INLINE
float
glm_vec4_distance(vec4 a, vec4 b) {
  vec4 tmp;
  glm_vec4_sub(a, b, tmp);
  return glm_vec4_norm(tmp);
}
```

because `glm_vec4_sub` and `glm_vec4_norm` is optimized and they are inline, it uses temp variable but compiler may generate same instructions. I tested both on godbolt, it seems compiler generates extra instructions for second one for ARM :( So first one seems better for now.

**Comment by haxpor** [comment]
Ok! Thank you for detailed guideline! That's complete solution already but I can learn something.
I'll get back to this tonight, or at worst within a few days.

**Comment by recp** [comment]
Fixed in https://github.com/recp/cglm/pull/84
