### ISSUE TITLE
Can't build release v0.5.3

### ISSUE THREAD

**Issue by BrentFarris** [recp/cglm#85]
Below is the output of make:
```
pi@raspberrypi:~/Development Libraries/cglm $ make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash "/home/pi/Development Libraries/cglm/missing" autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
make  all-am
make[1]: Entering directory '/home/pi/Development Libraries/cglm'
  CC       src/euler.lo
In file included from src/../include/cglm/cglm.h:14:0,
                 from src/euler.c:8:
src/../include/cglm/mat4.h:173:48: error: unknown type name ‘size_t’
 glm_mat4_identity_array(mat4 * __restrict mat, size_t count) {
                                                ^~~~~~
In file included from src/../include/cglm/cglm.h:15:0,
                 from src/euler.c:8:
src/../include/cglm/mat3.h:113:48: error: unknown type name ‘size_t’
 glm_mat3_identity_array(mat3 * __restrict mat, size_t count) {
                                                ^~~~~~
In file included from src/../include/cglm/cglm.h:19:0,
                 from src/euler.c:8:
src/../include/cglm/quat.h:116:48: error: unknown type name ‘size_t’
 glm_quat_identity_array(versor * __restrict q, size_t count) {
                                                ^~~~~~
makefile:905: recipe for target 'src/euler.lo' failed
make[1]: *** [src/euler.lo] Error 1
make[1]: Leaving directory '/home/pi/Development Libraries/cglm'
makefile:686: recipe for target 'all' failed
make: *** [all] Error 2
```

I resolved this issue by adding this into `include/cglm/mat4.h`:
```c
#include <stdlib.h>
```

However it still ends with another error I'm not so sure about:
```
ar: `u' modifier ignored since `D' is the default (see `U')
sh ./post-build.sh
ln: target '.libs/libcmocka.so.0' is not a directory
makefile:1773: recipe for target 'all-local' failed
make[1]: *** [all-local] Error 1
make[1]: Leaving directory '/home/pi/Development Libraries/cglm'
makefile:686: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by recp** [comment]
Hi @BrentFarris 

This is resolved with this PR: https://github.com/recp/cglm/pull/79 and **v0.5.4** will contain that commit and some other improvements.

**cmocka** only required if you want to run tests by running `make check`. You can see all build options at: https://cglm.readthedocs.io/en/latest/build.html

`./post-build.sh` contains a script like this:

```bash
if [ "$(uname)" = "Darwin" ]; then
  ln -sf $(pwd)/test/lib/cmocka/build/src/libcmocka.0.dylib \
      .libs/libcmocka.0.dylib;
else
  ln -sf $(pwd)/test/lib/cmocka/build/src/libcmocka.so.0 \
      .libs/libcmocka.so.0;
fi
```

if `build-deps.sh` is not run then this script should not be run either. This is a build bug, updated that script at: https://github.com/recp/cglm/commit/6e501ef1f66498d4f4e89de4a7d7d86491e9c41e

Can you pull master and rebuild? (v0.5.4 will contain this)

I'll try to create a directory like "Development Libraries" to test it again, because my folder names don't contain spaces

**Comment by BrentFarris** [comment]
Yeah, sorry. I just realized I was using spaces in the directory. I had to because I am working on something that came from Visual Studio land which doesn't care about the spaces for most things. I actually just changed it so that there isn't a space now because that broke other libraries like `curl` from building as well.

I'll pull down master and give it another go, thanks!

**Comment by recp** [comment]
@BrentFarris glad to see you can build it successfully. 

I have updated build script to allow spaces, so it should not be a problem anymore. 

I think we can close this issue now. (Re-open if I'm wrong please!)

Feel free to come with other issues or contributions ;)
