### ISSUE TITLE
squared distance

### ISSUE THREAD

**Issue by superbigio** [recp/cglm#95]
Hi, 
I am ready with a PR for a glm_vec4_distance_squared() function with support for SIMD, call and struct. I propose renaming the function distance_squared as opposed to distance2 like it currently is. Obviously I have #defines that allow calls to distance2 to be compiled successfully, but I think the distance2() name should be deprecated in favor of distance_squared(). If it is ok for you, I will send you a PR.

**Comment by recp** [comment]
Hi @superbigio 

`glm_vec4_distance_squared()` is too long. I would prefer to use shorter name like `glm_vec4_distance_sq()` or even `glm_vec4_dist_sq()`

But `_distance2` or `_norm2` is more like `pow(distance, 2)` or `distance ^ 2`, so I would prefer to keep existing name for now (`glm_vec3_distance2()`, `glm_vec4_distance2()`). It could be `glm_vec4_dist()` and `glm_vec4_dist2()` of course.

**Comment by superbigio** [comment]
ok, I'll keep the same naming convention then. (distance2, norm2, pow2, etc...)
I'll change it back in my fork and then I will be ready with a PR.

**Comment by recp** [comment]
https://github.com/recp/cglm/pull/96
