### ISSUE TITLE
glm_vec_broadcast() ---> glm_vec_fill()

### ISSUE THREAD

**Issue by superbigio** [recp/cglm#99]
I think all versions of glm_vec_broadcast() should be renamed to glm_vec_fill() which is shorter and more self-explanatory. If you agree I will create a PR.

**Comment by recp** [comment]
Hi @superbigio 

Of course a PR about this is welcome ;)

`_fill()` is good name. But let's not touch `broadcast` for now, it may be marked as deprecated later.

Unlike **broadcast**, please make vector as first parameter like:

```C
CGLM_INLINE
void
glm_vec3_fill(vec3 v, float val)
```

then we can call it like:

```C
glm_vec3_fill(max, 0.0f);
glm_vec3_fill(min, 1.0f);
```

I think first parameter is better place for vector.
